##########################################################
# Sample .aider.conf.yml
# This file lists *all* the valid configuration entries.
# Place in your home dir, or at the root of your git repo.
##########################################################

# Настройки Git
git: true
gitignore: true
auto-commits: true
dirty-commits: true
attribute-co-authored-by: true

# Настройки кэширования
cache-prompts: true
cache-keepalive-pings: 0

# Настройки репозитория
map-refresh: auto
map-multiplier-no-files: 2

# Файлы истории
input-history-file: .aider.input.history
chat-history-file: .aider.chat.history.md
restore-chat-history: false

# Настройки вывода
pretty: true
stream: true
user-input-color: "#00cc00"
tool-error-color: "#FF2222"
tool-warning-color: "#FFA500"
assistant-output-color: "#0088ff"
code-theme: default
show-diffs: false

# Настройки проверки кода
auto-lint: true
test-cmd: pytest
auto-test: true

# Аналитика и обновления
analytics: true
check-update: true
show-release-notes: null

# Безопасность
verify-ssl: true
check-model-accepts-settings: true
show-model-warnings: true

# Другие настройки
suggest-shell-commands: true
fancy-input: true
multiline: false
notifications: false
detect-urls: true
encoding: utf-8
line-endings: platform

# Контекстные файлы для чтения
read:
  - docs/data.md             # Существующий: данные хакатона
  - docs/evaluation.md       # Существующий: метрики оценки
  - docs/task.md             # Существующий: задание хакатона
  - plan.md                  # Существующий: план проекта
  - data/processed/train.csv # Существующий: обучающие данные
  - data/processed/test.csv  # Существующий: тестовые данные
  - scripts/generate_submission.py  # Существующий: генерация submission
  - scripts/calculate_metrics.py    # Существующий: расчёт метрик
  - src/app/adapters/finam_client.py  # Существующий: клиент API
  - src/app/core/llm.py             # Существующий: LLM-интеграция
  - src/app/interfaces/chat_app.py  # Существующий: Streamlit UI
  - .aider.model.settings.yml       # Существующий: настройки моделей
  - example.docs/create/  # файлы для генерации проекта и справки
